/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creacionales;

import Concrete_builder.AudiQ2;
import Concrete_builder.Camaro;
import Concrete_builder.Mustang;
import Fabrica_abstracta.CarroBuilder;
import Productos.carro;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import luces.Luces;

/**
 *
 * @author david
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    construir_carro obj = new construir_carro();
    Luces inst = Luces.getLuces();
    ImagenFondo fondo = new ImagenFondo();

    public Interfaz() {
        this.setContentPane(fondo);
        initComponents();
        grupo_botones.add(jRadioButton1);
        grupo_botones.add(jRadioButton2);
        grupo_botones.add(jRadioButton3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        lblChasis = new javax.swing.JLabel();
        lblRuedas = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        lblLuces = new javax.swing.JLabel();
        jpCamaro = new ImgCamaro();
        jpAudiQ2 = new ImgAudi();
        jpMustang = new ImgMustang();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(740, 520));
        setMinimumSize(new java.awt.Dimension(740, 520));
        getContentPane().setLayout(null);

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Camaro");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(22, 46, 151, 23);

        lblChasis.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        lblChasis.setForeground(new java.awt.Color(255, 255, 255));
        lblChasis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblChasis);
        lblChasis.setBounds(162, 264, 404, 19);

        lblRuedas.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        lblRuedas.setForeground(new java.awt.Color(255, 255, 255));
        lblRuedas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblRuedas);
        lblRuedas.setBounds(162, 289, 404, 19);

        lblMotor.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        lblMotor.setForeground(new java.awt.Color(255, 255, 255));
        lblMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMotor);
        lblMotor.setBounds(162, 239, 404, 19);

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("AudiQ2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(268, 51, 158, 23);

        jLabel1.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESCOJA EL AUTO DE SU PREFERENCIA PARA VER LAS ESPECIFICACIONES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(47, 11, 630, 33);

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Mustang1970");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseExited(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(538, 51, 116, 23);

        lblLuces.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        lblLuces.setForeground(new java.awt.Color(255, 255, 255));
        lblLuces.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblLuces);
        lblLuces.setBounds(162, 314, 404, 19);

        jpCamaro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jpCamaroLayout = new javax.swing.GroupLayout(jpCamaro);
        jpCamaro.setLayout(jpCamaroLayout);
        jpCamaroLayout.setHorizontalGroup(
            jpCamaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpCamaroLayout.setVerticalGroup(
            jpCamaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jpCamaro);
        jpCamaro.setBounds(22, 71, 151, 150);

        jpAudiQ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jpAudiQ2Layout = new javax.swing.GroupLayout(jpAudiQ2);
        jpAudiQ2.setLayout(jpAudiQ2Layout);
        jpAudiQ2Layout.setHorizontalGroup(
            jpAudiQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jpAudiQ2Layout.setVerticalGroup(
            jpAudiQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        getContentPane().add(jpAudiQ2);
        jpAudiQ2.setBounds(268, 76, 174, 145);

        jpMustang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jpMustangLayout = new javax.swing.GroupLayout(jpMustang);
        jpMustang.setLayout(jpMustangLayout);
        jpMustangLayout.setHorizontalGroup(
            jpMustangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jpMustangLayout.setVerticalGroup(
            jpMustangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jpMustang);
        jpMustang.setBounds(538, 76, 164, 145);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        CarroBuilder obj1 = new Camaro();

        // guarda una instacia de la clase Camion_uno en la variable
        obj.setcarroBuilder(obj1); // setea obj1 para hacer la creacion del camion
        obj.fabrica_camion(); // // ejecuta el metodo fabrica_camion de la clase construir_camion
        carro nueva = obj.getcarro(); // pide el camion creado para darle valor a la variable nueva
        lblMotor.setText("Motor del carro escogido: " + nueva.getMotor());
        lblChasis.setText("Chasis del carro escogido: " + nueva.getCarroceria());
        lblRuedas.setText("Ruedas del carro escogido: " + nueva.getRuedas());
        lblLuces.setText(inst.inst("Las luces del carro escogido son led"));
        //lblLuces.setText("Las luces del carro son " + luc.getTipo());

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        CarroBuilder obj1 = new AudiQ2(); // guarda una instacia de la clase Camion_uno en la variable
        obj.setcarroBuilder(obj1); // setea obj1 para hacer la creacion del camion
        obj.fabrica_camion(); // // ejecuta el metodo fabrica_camion de la clase construir_camion
        carro nueva = obj.getcarro(); // pide el camion creado para darle valor a la variable nueva
        lblMotor.setText("Motor del carro escogido: " + nueva.getMotor());
        lblChasis.setText("Chasis del carro escogido: " + nueva.getCarroceria());
        lblRuedas.setText("Ruedas del carro escogido: " + nueva.getRuedas());
        lblLuces.setText(inst.inst("Las luces del carro escogido son led"));
        //lblLuces.setText("Las luces del carro son " + nueva.setLuz());
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

        CarroBuilder obj1 = new Mustang(); // guarda una instacia de la clase Camion_uno en la variable
        obj.setcarroBuilder(obj1); // setea obj1 para hacer la creacion del camion
        obj.fabrica_camion(); // // ejecuta el metodo fabrica_camion de la clase construir_camion
        carro nueva = obj.getcarro(); // pide el camion creado para darle valor a la variable nueva
        lblMotor.setText("Motor del carro escogido: " + nueva.getMotor());
        lblChasis.setText("Chasis del carro escogido: " + nueva.getCarroceria());
        lblRuedas.setText("Ruedas del carro escogido: " + nueva.getRuedas());
        lblLuces.setText(inst.inst("Las luces del carro escogido son led"));
        //lblLuces.setText("Las luces del carro son " + nueva.setLuz());
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseExited
        System.out.println("");// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel jpAudiQ2;
    private javax.swing.JPanel jpCamaro;
    private javax.swing.JPanel jpMustang;
    private javax.swing.JLabel lblChasis;
    private javax.swing.JLabel lblLuces;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblRuedas;
    // End of variables declaration//GEN-END:variables

    class ImagenFondo extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("Fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    class ImgCamaro extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("Camaro.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    class ImgAudi extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("AudiQ2.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    class ImgMustang extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("Mustang.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
